### ISSUE TITLE
explain what this repo does, in relation to music-suite

### ISSUE THREAD

**Issue by jwaldmann** [ejlilley/lilypond-parse#2]
Currently, this repo here has just one module Data.Music.Lilypond.Parse but in fact it contains
* data type declarations (an AST for Lilypond expressions/files)
* an AST printer (`instance Show ...`)
* the actual parser (`parseLily`)
* semantics functions (e.g., `:: LilySequential -> LilySequential) -> LilyExpr -> LilyExpr`)

The goal is intergration with `music-suite`, which already has an AST type and a printer (`data Music`, `instance  Pretty Music`) and some semantics,  https://github.com/music-suite/music-suite/blob/master/src/Data/Music/Lilypond.hs . This should be merged somehow. What would be the best way forward?

**Comment by ejlilley** [comment]
This repo was split off from another repo, [AbstractMusic](https://github.com/ejlilley/AbstractMusic) -- it wasn't designed from the ground up to be integrated into the music-suite (some other features from AbstractMusic have been ported to music-suite though, such as the internal representation of intervals).
